name: Deploy to GCP VM

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies & Build
        run: |
          npm install
          npm run build

      - name: Upload Files to VM
        uses: burnett01/rsync-deployments@v7.0.1
        with:
          switches: -avzr --delete
          remote_path: /home/akchanchal2002/app/
          remote_host: ${{ secrets.VM_HOST }}
          remote_user: ${{ secrets.VM_USER }}
          remote_key: ${{ secrets.VM_SSH_KEY }}

      - name: Restart PM2 on VM
        run: |
          ssh -i <(echo "${{ secrets.VM_SSH_KEY }}") -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "
            cd /home/ubuntu/app &&
            npm install --omit=dev &&
            pm2 restart nestapp || pm2 start dist/main.js --name nestapp
          "
